### ISSUE TITLE
TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by Zrufy** [T-Almeida/tensorflow-keras-multidimensional-rnn#3]
Thank you for the work done for this project. I noticed a problem with inserting input_shape in a functional model with keras. Do you have any solution?

```
    gru_1 = MultiDimensionalRNN(MultiDimensinalGRUCell(4, activation='tanh'),input_shape(5,5,1))(inner)
TypeError: 'tuple' object is not callable
```

**Comment by T-Almeida** [comment]
Hi, 

Thanks for the feedback 🙂... Unfortunetly, and due to lack of time, I am not updating at the rate I would like to. Besides, I am not yet pleased with the achieded performance, which will be my next focus.

The problem seems to be a typo that I have made on the README file. The correct one should be:
"input_shape=(5,5,1)" that follows the [Sequential API from Keras ](https://www.tensorflow.org/api_docs/python/tf/keras/Sequential)

I also added a [notebook](https://github.com/T-Almeida/tensorflow-keras-multidimensional-rnn/blob/master/notebooks/3%20-%20Simple%20use%20case.ipynb) to demonstrate this use case:
